// resources/[dg]/dg-phone/ui/src/components/os/ImageContainer.vue
<template class="image-container">
	<span v-if="isClicked" class="image-container--span" @click.prevent="toggleImage(false)">Click here to hide</span>
	<div class="image-container--wrapper">
		<div
			v-if="isClicked"
			@mouseenter.prevent="toggleBigImage(true)"
			@mouseleave.prevent="toggleBigImage(false)"
			@click.prevent="copyToClipboard(imageUrl)"
		>
			<img :src="imageUrl" alt="an image" />
		</div>
		<div v-else class="image-container--hidden" @click="toggleImage(true)">
			<i class="fas fa-eye-slash"></i>
			<p>Click to view this image</p>
		</div>
	</div>
</template>

<script lang="ts">
	import { defineComponent, ref } from 'vue';
	import '@/styles/os/ImageContainer.scss';
	import { copyToClipboard } from '../../lib/nui';
	import { useStore } from '../../lib/state';

	export default defineComponent({
		props: {
			imageUrl: {
				type: String,
				required: true,
			},
		},
		setup(props) {
			const store = useStore();
			const isClicked = ref(false);
			const toggleImage = (toggle: boolean) => {
				isClicked.value = toggle;
			};
			const toggleBigImage = (toggle: boolean) => {
				if (!isClicked.value) return;
				store.commit('setAppState', {
					appName: 'bigPicture',
					data: toggle ? props.imageUrl : undefined,
				});
			};
			return {
				toggleImage,
				isClicked,
				toggleBigImage,
				copyToClipboard,
			};
		},
	});
</script>

// resources/[dg]/dg-ui/[src]/src/components/imagecontainer.tsx
import React, { FC, useState } from 'react';
import { CircularProgress } from '@mui/material';

import { copyToClipboard } from '../lib/util';
import { setBigPhoto } from '../main/phone/lib';
import { styles } from '../styles/components/imagecontainer.styles';

export const Imagecontainer: FC<{
  url: string;
  loading: boolean;
}> = props => {
  const [isClicked, setIsClicked] = useState(false);
  const classes = styles();

  const handleShowBig = () => {
    if (props.loading || !isClicked) return;
    setBigPhoto(props.url);
  };

  const handleHideBig = () => {
    setBigPhoto(null);
  };

  return (
    <div className={classes.root}>
      {isClicked && (
        <span className={classes.hideSpan} onClick={() => setIsClicked(false)}>
          Click here to hide the image
        </span>
      )}
      <div className={classes.wrapper} onMouseEnter={handleShowBig} onMouseLeave={handleHideBig}>
        {props.loading ? (
          <div className={classes.spinner}>
            <CircularProgress color={'inherit'} />
          </div>
        ) : isClicked ? (
          <div onClick={() => copyToClipboard(props.url)}>
            <img src={props.url} alt='image' />
          </div>
        ) : (
          <div className={classes.hidden} onClick={() => setIsClicked(true)}>
            <i className='fas fa-eye-slash'></i>
            <p>Click to view this image</p>
          </div>
        )}
      </div>
    </div>
  );
};
