// resources/[dg]/dg-ui/[src]/src/main/phone/apps/contacts-app/components/contacts.tsx
import React, { FC } from 'react';

import { Paper } from '../../../../../components/paper';
import { ConfirmationModal } from '../../../../../components/util';
import { nuiAction } from '../../../../../lib/nui-comms';
import { copyToClipboard } from '../../../../../lib/util';
import { showCheckmarkModal, showFormModal } from '../../../lib';
import { openConversation } from '../../message-app/lib';
import { startPhoneCall } from '../../phone-app/lib';
import { fetchContacts } from '../lib';

import { styles } from './contacts.styles';
import { ContactModal } from './modals';

export const Contacts: FC<{ contacts: Phone.Contacts.Contact[] }> = props => {
  const classes = styles();

  const actions: Action[] = [
    {
      title: 'Bewerk',
      icon: 'pencil',
      onClick: (c: Phone.Contacts.Contact) => {
        showFormModal(<ContactModal contact={c} type={'edit'} />);
      },
    },
    {
      title: 'Verwijder',
      icon: 'trash-alt',
      onClick: (c: Phone.Contacts.Contact) => {
        showFormModal(
          <ConfirmationModal
            header={'Weet je zeker dat je dit contact wilt verwijderen?'}
            onAccept={async () => {
              await nuiAction('phone/contacts/delete', {
                id: c.id,
              });
              showCheckmarkModal(() => fetchContacts());
            }}
          />
        );
      },
    },
    {
      title: 'Bel',
      icon: 'phone',
      onClick: (c: Phone.Contacts.Contact) => {
        startPhoneCall(c.phone);
      },
    },
    {
      title: 'SMS',
      icon: 'comment-alt',
      onClick: (c: Phone.Contacts.Contact) => {
        openConversation(c.phone);
      },
    },
    {
      title: 'Kopieer',
      icon: 'clipboard',
      onClick: (c: Phone.Contacts.Contact) => {
        copyToClipboard(c.phone);
      },
    },
  ];

  return (
    <div className={classes.root}>
      {props.contacts.map(c => (
        <Paper
          key={c.id}
          title={c.label}
          description={c.phone}
          image={'user-circle'}
          actions={actions.map(a => ({ ...a, data: c }))}
        />
      ))}
    </div>
  );
};

// resources/[dg]/dg-phone/ui/src/components/apps/contacts/Contacts.vue
<template>
	<app-container :primary-actions="primActions" :search="searchInfo">
		<div class="contact-wrapper">
			<paper v-for="contact in filteredList" :key="contact.id" :actions="paperActions" :handler-arg="[contact]">
				<template #image>
					<i class="fas fa-user-circle"></i>
				</template>
				<template #title>{{ contact.label }}</template>
				<template #description>{{ contact.phone }}</template>
			</paper>
		</div>
	</app-container>
</template>

<script lang="ts">
	import AppContainer from '../../os/AppContainer.vue';
	import { Action, Search } from '../../../types/appcontainer';
	import { useStore } from '../../../lib/state';
	import Paper from '../../os/Paper.vue';
	import { Contact } from '../../../types/apps';
	import { AddContactForm, EditContactForm, RemoveContactForm } from './components/ContactForm.vue';
	import { startPhoneCall } from '../../../lib/call';
	import { computed, defineComponent, onMounted, onRenderTriggered, ref } from 'vue';
	import { fetchContacts } from './lib';
	import { copyToClipboard } from '../../../lib/nui';
	import '@/styles/apps/contacts.scss';

	export default defineComponent({
		components: { Paper, AppContainer },
		setup() {
			const primActions: Action[] = [
				{
					icon: 'plus',
					label: 'New contact',
					handler: () => {
						store.dispatch('openModal', {
							element: AddContactForm,
							props: {},
						});
					},
				},
			];
			const paperActions: Action<Contact>[] = [
				{
					icon: 'phone-alt',
					label: 'Call',
					handler: c => {
						startPhoneCall(c.phone);
					},
				},
				{
					icon: 'comment-alt',
					label: 'Messsage',
					handler: c => {
						store.dispatch('openMsgConvo', c.phone);
					},
				},
				{
					icon: 'pencil',
					label: 'Edit',
					handler: c => {
						store.dispatch('openModal', {
							element: EditContactForm,
							props: {
								contact: c,
							},
						});
					},
				},
				{
					icon: 'trash-alt',
					label: 'Remove',
					handler: c => {
						store.dispatch('openModal', {
							element: RemoveContactForm,
							props: {
								contact: c,
							},
						});
					},
				},
				{
					icon: 'clipboard',
					label: 'Copy',
					handler: c => {
						copyToClipboard(c.phone);
					},
				},
			];
			const store = useStore();
			const contacts = computed<Contact[]>(() => {
				return store.state.contacts;
			});
			const filteredList = ref<Contact[]>(contacts.value);
			const searchInfo = ref<Search>({
				list: contacts.value,
				filter: ['label'],
				onChange: contacts => {
					filteredList.value = contacts;
				},
			});
			const fetchContactsInternal = async () => {
				filteredList.value = await fetchContacts();
			};
			onMounted(fetchContactsInternal);
			onRenderTriggered(fetchContactsInternal);
			return {
				primActions,
				searchInfo,
				paperActions,
				filteredList,
			};
		},
	});
</script>
