// resources/[dg]/dg-phone/ui/src/components/apps/crypto-app/components/modals.tsx
import { defineComponent, PropType } from 'vue';
import { CoinEntry } from '../../../../types/apps';
import SimpleForm from '@/components/os/SimpleForm.vue';
import { FormInput } from '../../../../types/simpleform';
import { nuiAction } from '../../../../lib/nui';
import { useStore } from '../../../../lib/state';

export const ExchangeModal = defineComponent({
	name: 'ExchangeModal',
	components: {
		SimpleForm,
	},
	props: {
		coin: {
			type: Object as PropType<CoinEntry>,
			required: true,
		},
	},
	setup(props) {
		const store = useStore();
		const inputs: FormInput[] = [
			{
				type: 'contacts',
				name: 'target',
			},
			{
				type: 'number',
				name: 'amount',
				label: 'Amount',
				min: 0,
				max: props.coin.wallet.amount,
			},
		];
		const onSubmit = async (data: { amount: string | number; target: string }) => {
			data.amount = parseInt(data.amount as string);
			if (data.amount == 0 || isNaN(data.amount)) return;
			await nuiAction('crypto/transfer', { ...data, coin: props.coin.crypto_name });
			store.dispatch('openCheckmarkModal', () => {
				store.dispatch('refreshCoins');
			});
		};
		return () => <SimpleForm inputs={inputs} onAccept={onSubmit} />;
	},
});

export const PurchaseModal = defineComponent({
	name: 'PurchaseModal',
	components: {
		SimpleForm,
	},
	props: {
		coin: {
			type: Object as PropType<CoinEntry>,
			required: true,
		},
	},
	setup(props) {
		const store = useStore();
		const inputs: FormInput[] = [
			{
				type: 'number',
				name: 'amount',
				label: 'Amount',
				min: 0,
			},
		];
		const onSubmit = async (data: { amount: string | number }) => {
			data.amount = parseInt(data.amount as string);
			if (data.amount == 0 || isNaN(data.amount)) return;
			await nuiAction('crypto/purchase', { ...data, coin: props.coin.crypto_name });
			store.dispatch('openCheckmarkModal', () => {
				store.dispatch('refreshCoins');
			});
		};
		return () => <SimpleForm inputs={inputs} onAccept={onSubmit} />;
	},
});

// resources/[dg]/dg-ui/[src]/src/main/phone/apps/crypto-app/components/modals.tsx
import React, { FC } from 'react';

import { Input } from '../../../../../components/inputs';
import { SimpleForm } from '../../../../../components/simpleform';
import { nuiAction } from '../../../../../lib/nui-comms';
import { genericAction, showCheckmarkModal } from '../../../lib';

const setDirty = () => {
  genericAction('phone.apps.crypto', {
    shouldRenew: true,
  });
};

export const ExchangeModal: FC<{ coin: Phone.Crypto.Coin }> = ({ coin }) => (
  <SimpleForm
    elements={[
      {
        name: 'target',
        render: props => <Input.Contact {...props} icon={'mobile'} />,
      },
      {
        name: 'amount',
        render: props => <Input.Number {...props} min={0} max={coin.wallet.amount} label={'Amount'} icon={'coins'} />,
      },
    ]}
    onAccept={async (vals: { target: string; amount: string | number }) => {
      vals.amount = parseInt(vals.amount as string);
      if (vals.amount <= 0 || vals.amount > coin.wallet.amount || isNaN(vals.amount)) return;
      await nuiAction('phone/crypto/transfer', { ...vals, coin: coin.crypto_name });
      showCheckmarkModal(setDirty);
    }}
  />
);

export const PurchaseModal: FC<{ coin: Phone.Crypto.Coin }> = ({ coin }) => (
  <SimpleForm
    elements={[
      {
        name: 'amount',
        render: props => <Input.Number {...props} min={0} label={'Amount'} icon={'coins'} />,
      },
    ]}
    onAccept={async (vals: { target: string; amount: string | number }) => {
      vals.amount = parseInt(vals.amount as string);
      if (vals.amount <= 0 || isNaN(vals.amount)) return;
      await nuiAction('phone/crypto/purchase', { ...vals, coin: coin.crypto_name });
      showCheckmarkModal(setDirty);
    }}
  />
);
