// resources/[dg]/dg-ui/[src]/src/components/list.tsx
import React, { FC } from 'react';

import { styles } from '../styles/components/list.styles';

import { Icon } from './icon';

export const List: FC<{ items: ListItem[] }> = props => {
  const classes = styles();
  return (
    <div className={classes.list}>
      {props.items.map(e => (
        <div key={e.label + e.icon} className={classes.entry}>
          {e.icon && (
            <div className={'icon'}>
              <Icon name={e.icon} size={e.size ?? '1rem'} />
            </div>
          )}
          <div className={'text'}>{e.label}</div>
        </div>
      ))}
    </div>
  );
};

// resources/[dg]/dg-phone/ui/src/components/os/List.vue
<template>
	<div class="phone-list">
		<div v-for="(entry, i) in items" :key="i" class="phone-list--entry">
			<div v-if="entry.icon" class="phone-list--entry--icon">
				<q-icon :name="entry.icon" :size="entry?.size ?? '1rem'"></q-icon>
			</div>
			<div class="phone-list--entry--text">
				{{ entry.label }}
			</div>
		</div>
	</div>
</template>

<script lang="ts">
	import { defineComponent, PropType } from 'vue';
	import { ListEntry } from '../../types/list';
	import '@/styles/os/list.scss';

	export default defineComponent({
		name: 'List',
		props: {
			items: {
				type: Array as PropType<ListEntry[]>,
				required: true,
			},
		},
		setup() {
			return {};
		},
	});
</script>
