// resources/[dg]/dg-ui/[src]/src/main/phone/apps/home-screen/components/homescreen.tsx
import React, { FC, useMemo, useState } from 'react';
import { Tooltip } from '@mui/material';

import { Icon } from '../../../../../components/icon';
import { isDevel } from '../../../../../lib/env';
import { ConfigObject, getPhoneApps } from '../../../config';
import { changeApp } from '../../../lib';
import { AppContainer } from '../../../os/appcontainer/appcontainer';

import { styles } from './homescreen.styles';

const AppIcon: FC<ConfigObject> = props => {
  const classes = styles();
  return (
    <Tooltip
      placement={'top'}
      arrow
      title={isDevel() ? `${props.name} | ${props.label} (${props.position})` : props.label}
    >
      <div
        className={classes.app}
        onClick={() => changeApp(props.name)}
        style={{
          color: props.icon?.color ?? 'white',
          background: `linear-gradient(transparent, ${props.icon.backgroundGradient ?? 'rgba(0, 0, 0, 0)'})`,
          backgroundColor: props.icon.background ?? '#000',
        }}
      >
        <Icon lib={props.icon.lib} name={props.icon.name} size={props.icon.size ?? '1.5rem'} />
      </div>
    </Tooltip>
  );
};
const EmptyIcon = () => {
  const classes = styles();
  return <div className={classes.app} style={{ background: 'none', boxShadow: 'none' }} />;
};

export const HomeScreen = () => {
  const [apps, setApps] = useState<any[]>([]);
  const classes = styles();
  useMemo(() => {
    const _apps = getPhoneApps().filter(c => !!c.icon && (c.hidden ? !c.hidden() : true));
    const missingAmount = 4 - (_apps.length % 4);
    missingAmount === 4 ? setApps(_apps) : setApps(_apps.concat(new Array(missingAmount).fill({ empty: true })));
  }, []);
  return (
    <AppContainer>
      <div className={classes.root}>
        {apps.map((a, i) => (a.empty ? <EmptyIcon key={i} /> : <AppIcon key={a.name} {...a} />))}
      </div>
    </AppContainer>
  );
};

// resources/[dg]/dg-phone/ui/src/components/apps/home-screen/HomeScreen.vue
<template>
	<app-container>
		<div class="home-screen">
			<div v-for="app in apps" :key="app">
				<div
					v-if="!app.empty"
					v-tooltip="isDev() ? `[${app.position}] ${app.name}` : app.label"
					class="home-screen-app"
					:style="
						(!app?.empty && {
							color: app?.icon?.color ?? 'white',
							background: `linear-gradient(transparent, ${app?.icon?.backgroundGradient ?? 'rgba(0, 0, 0, 0.3)'})`,
							'background-color': app?.icon?.background ?? '#000',
						}) || {
							background: 'none',
						}
					"
					@click="!app?.empty && selectApp(app.name)"
				>
					<q-icon
						:name="`${app?.icon?.lib ?? 'fas fa-'}${app?.icon?.name ?? 'house'}`"
						:size="`${app?.icon?.size}rem` ?? '2rem'"
					></q-icon>
				</div>
			</div>
		</div>
	</app-container>
</template>

<script>
	import '@/styles/home-screen.scss';
	import { defineComponent } from 'vue';
	import AppContainer from '@/components/os/AppContainer.vue';
	import { phoneApps } from '../../../lib/apps';
	import { useStore } from '../../../lib/state';
	import { isDev } from '../../../lib/util';

	export default defineComponent({
		name: 'HomeScreen',
		components: { AppContainer },
		setup() {
			const store = useStore();
			const filteredApps = Object.values(phoneApps)
				.filter(app => !!app.icon && (app.hidden ? !app.hidden() : true))
				.sort((a, b) => (a.position < b.position ? -1 : 1));
			const missing = 4 - (filteredApps.length % 4);
			const emptyApps = new Array(missing).fill({ empty: true });
			filteredApps.push(...emptyApps);

			const selectApp = app => {
				store.commit('setActiveApp', app);
			};
			return {
				apps: filteredApps,
				selectApp,
				isDev,
			};
		},
	});
</script>

<style scoped></style>
